### ISSUE TITLE
误杀太严重

### ISSUE THREAD

**Issue by inused** [clion007/dnsmasq#3]
看了下脚本，下载的一些ad host之类的规则误杀好严重，很多都是把一些非ad域名直接给干掉了，有一个直接把meizu.com这个域名全干掉了
那一些看起来不像是单纯的去广告，更像是不喜欢哪个产品就直接把他干掉，太偏激了。
如果是完全是写出来仅供个人使用的话还没啥，但是这个明显不是
希望可以尽量舍弃那些个人倾向非常严重的ad规则

**Comment by clion007** [comment]
广告规则都是来自网友维护的，误杀的可以自己添加白名单就解决了
