### ISSUE TITLE
这个脚本对于翻墙好像太繁琐了

### ISSUE THREAD

**Issue by chainofhonor** [clion007/dnsmasq#4]
dnsmasq是支持通配符的
比如设置特殊域名走特定的dns服务器
echo "server=/google.com/8.8.8.8" >> /etc/dnsmasq.d/server.conf 
所有*.google.com的解析全部转发到8.8.8.8这个DNS服务器来进行解析
然后让8.8.8.8自动走ss通道
这样我们只需要维护这个server.conf的列表就行了
这个列表应该没有多大

我刚刚看了下你总结的那个表，800多KB，太大了，里面全部是address，应该适当的合理使用上面我说的功能

而且单纯的dnsmasq是没什么用的（就算你现在host正确，但是只要你一访问，就被GFW知道了），必须要配合ss或者其他vpn工具

**Comment by clion007** [comment]
写这个的时候还可以用的，后来GFW升级了，单纯的不好使了
