### ISSUE TITLE
白名单不生效的问题

### ISSUE THREAD

**Issue by freeskyfly** [clion007/dnsmasq#5]
发现用户白名单以及系统自带的白名单不生效。
我测试了下deletWhiteListRules.sh是正常的。
但问题是：
while read -r line
do
	if [ -s "/tmp/dnsrules.conf" ]; then 
		sed -i "/$line/d" /tmp/dnsrules.conf
	elif [ -s "/tmp/hostsrules.conf" ]; then 
		sed -i "/$line/d" /tmp/hostsrules.conf
	fi
done < /tmp/whitelist
检测/tmp下的这两个文件其实是不存在的，前面的getDnsmasqAdRules.sh，getHostsAdRules.sh生成的文件叫dnsAd&hostsAd。所以这个脚本实际上执行后没有效果。

另外，即便执行有效，在主程序中
mv /tmp/dnsrules.conf /etc/dnsmasq.d/dnsrules.conf
mv /tmp/hostsrules.conf /etc/dnsmasq/hostsrules.conf
sort /tmp/dnsAd | uniq >> /etc/dnsmasq.d/dnsrules.conf
sort /tmp/hostsAd | uniq >> /etc/dnsmasq/hostsrules.conf
也会把被去掉的部分又覆盖进来。

我觉得应该是把几个脚本文件名统一一下。统一成dnsAd&hostsAd
然后删掉主程序里面的mv命令。
也就是执行白名单后，去重，覆盖。

**Comment by freeskyfly** [comment]
另外，发现根据目前的adwhitelist文件，处理两个conf文件估计要半小时吧

**Comment by clion007** [comment]
非常感谢对bug的反馈！
这里确实有问题，重新写脚本结构后，这里没有注意出了bug；
我再次检查了脚本的运行逻辑，文件的覆盖和去重没有问题，只需要将deletWhiteListRules.sh脚本中的文件名分别改成对应的dnsAd&hostsAd就可以了；
我已经更新了脚本，再次感谢指正！
